name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.PUBLIC_KEY }}"
      - name: echo a secret
        run: echo "your secret token is ${{ secrets.PUBLIC_KEY }}"
