name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          BRANCH: gh-pages
          FOLDER: public
          BUILD_SCRIPT: yarn && yarn run build
