name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.PUBLIC_KEY }}"
      - name: echo a secret
        run: echo "your secret token is ${{ secrets.PUBLIC_KEY }}"
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Verificar archivos
        run: ls -la

      - name: Ejecutar script JavaScript
        run: |
          echo "Initializing EmailJS with secret key..."
          ls -la js/ # Verifica el contenido del directorio js
          sed -i 's/emailjs.init("[^"]*");/emailjs.init("${{ secrets.PUBLIC_KEY }}");/' js/app.js
          node js/app.js
        env:
          SECRET_TOKEN: ${{ secrets.PUBLIC_KEY }}
